{
    "assignee": null,
    "body": "Hi, i'm getting no_routes error when using yowsup in python. Any clues ? \r\n\r\nIt was working perfectly for the pass 2 week and getting this error since this morning.",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1099/comments",
    "created_at": "2015-02-03T11:52:02Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1099/events",
    "html_url": "https://github.com/venomous0x/WhatsAPI/issues/1099",
    "id": 56367813,
    "labels": [],
    "labels_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1099/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1099,
    "state": "open",
    "title": "No routes",
    "updated_at": "2015-02-03T11:53:04Z",
    "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1099",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/10219492?v=3",
        "events_url": "https://api.github.com/users/new-user1/events{/privacy}",
        "followers_url": "https://api.github.com/users/new-user1/followers",
        "following_url": "https://api.github.com/users/new-user1/following{/other_user}",
        "gists_url": "https://api.github.com/users/new-user1/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/new-user1",
        "id": 10219492,
        "login": "new-user1",
        "organizations_url": "https://api.github.com/users/new-user1/orgs",
        "received_events_url": "https://api.github.com/users/new-user1/received_events",
        "repos_url": "https://api.github.com/users/new-user1/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/new-user1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/new-user1/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/new-user1"
    }
}